name: 'prlint'
description: 'A GitHub action that checks that pull requests title, body, branch name matches regex patters.'
author: 'Patrick Kempff <patrickkempff@gmail.com'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the pr lint configurations'
    default: '.github/prlint.yml'
  report-title:
    description: 'The title of the report table'
    default: 'Report'    
  report-intro:
    description: 'The intro of the report, rendered above the table'
    default: |
      :wave:
  report-message:
    description: 'The message of the report, rendered below the table'
    default: >
      ### Thank you for your effort by submitting this PR! 👍

      I am here to help you analyzing changes you have submitted :-). Everytime you make a change I will report back to you by updating this exact comment.
      :pray: Before this PR can be reviewed, please resolve the issues first. Thanks!
      
      **Not sure how to resolve a specific issue?** 
      There are edge cases where I will be wrong. If you think this is the case or you are not sure how to fix the issue, you should let the reviewer know by adding the reason/question to your PR description. If you are looking for me or want to know what rules I live by, you can find me in [dangerfile.js](../blob/master/dangerfile.js).
      
      <p align="right">Generated by :no_entry_sign: <a href="https://github.com/features/actions">GitHub Action</a> against {{commit}}</p>

runs:
  using: 'node12'
  main: 'dist/index.js'

