name: 'prlint'
description: 'A GitHub action that checks that pull requests title, body, branch name matches regex patters.'
author: 'Patrick Kempff <patrickkempff@gmail.com'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the pr lint configurations'
    default: '.github/prlint.yml'

  comment-table-header:
    description: 'The title of the report table'
    default: 'Fails'  

  comment-intro:
    description: 'The intro of the report, rendered above the table'
    default: |+
      :wave: Hi There! 

      I am here to help you by making sure your PR meets our creteria for review :-). Everytime you make a change I will report back to you by updating this exact comment. 

  comment-body:
    description: 'The message of the report, rendered below the table'
    default: >   
      I found **{{count}}** failures but please don't let this discourage you! Your effort is greatly appreciated and together we make sure that the codebase stays in awesome shape! :ok_hand:

      :pray: Before this PR can be reviewed, please resolve the above issues first. Thanks! 

      **Not sure how to resolve a specific issue?** 
      There are edge cases where I will be wrong. If you think this is the case or you are not sure how to fix the issue, you should let the reviewer know by adding the reason/question to your PR description. If you are looking for me or want to know what rules I live by, you can find me in [prlint.yml](../blob/master/.github/prlint.yml).

runs:
  using: 'node12'
  main: 'dist/index.js'

